# Generated by Django 5.2 on 2025-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='review_limit',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seconds_per_card',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
