# Generated by Django 5.2 on 2025-05-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_review_limit_quiz_seconds_per_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='seconds_per_card',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
