# Generated by Django 5.2 on 2025-04-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='deck',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
