# Generated by Django 5.2.1 on 2025-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_deck_description_deck_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='fsrs',
            field=models.JSONField(null=True),
        ),
    ]
