name: Lint and Test

on: [push]

env:
  DATABASE_URL: "sqlite:////db.sqlite3"
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Analyse with djlint
      run: |
        djlint .
    - name: Analyse with mypy
      run: |
        mypy .
    - name: Test
      run: |
        python manage.py test